version: '3.7'

services:
        analyzer-rewards:
                image: eth-state-analyzer:latest
                build:
                        context: ./
                        dockerfile: Dockerfile
                container_name: eth-state-analyzer-rewards
                init: true
                command: >-
                        rewards
                        --log-level=${STATE_ANALYZER_LOG_LEVEL}
                        --bn-endpoint=${STATE_ANALYZER_BN_ENDPOINT}
                        --init-slot=${STATE_ANALYZER_INIT_SLOT}
                        --final-slot=${STATE_ANALYZER_FINAL_SLOT}
                        --db-url=${STATE_ANALYZER_DB_URL}
                        --workers-num=${STATE_ANALYZER_WORKERS_NUM}
                        --db-workers-num=${STATE_ANALYZER_DB_WORKERS_NUM}
                        --download-mode=${STATE_ANALYZER_DOWNLOAD_MODE}
                        --custom-pools=${STATE_ANALYZER_POOLS_FILE}
                        --metrics=${STATE_ANALYZER_METRICS}
                        --missing-vals=${STATE_ANALYZER_MISSING_VALS}
                        
                network_mode: 'host'
                restart: unless-stopped
        
        analyzer-blocks:
                image: eth-state-analyzer:latest
                build:
                        context: ./
                        dockerfile: Dockerfile
                container_name: eth-state-analyzer-blocks
                init: true
                command: >-
                        blocks
                        --log-level=${STATE_ANALYZER_LOG_LEVEL}
                        --bn-endpoint=${STATE_ANALYZER_BN_ENDPOINT}
                        --init-slot=${STATE_ANALYZER_INIT_SLOT}
                        --final-slot=${STATE_ANALYZER_FINAL_SLOT}
                        --db-url=${STATE_ANALYZER_DB_URL}
                        --workers-num=1
                        --db-workers-num=1
                        --download-mode=${STATE_ANALYZER_DOWNLOAD_MODE}
                network_mode: 'host'
                restart: unless-stopped
                

                

        
        