version: '3.7'

services:
  analyzer:
    build:
      context: ./
      dockerfile: Dockerfile
    init: true
    command: >-
      blocks
      --env-file
    network_mode: 'host'
    restart: unless-stopped
